### ISSUE TITLE
[signup] 회원가입 API 구현

### ISSUE THREAD

**Issue by woorim960** [wooahan-agile/idu-market-server#3]
## 목적
> 유저 회원가입

## 구현 기능
- [x] API 설계
---
* Request

**URL :**  /api/student
**Method :** POST
**Content-type :** application/json; charset=utf-8
```js
{
   id: 유저 아이디 (type: String),
   name: 유저 이름 (type: String),
   nickname: 유저 별명 (type: String),
   email: 유저 이메일 (type: String),
   major: 유저 학과번호 (type: String),
   psword: 유저 비밀번호 (type: String)
}
```
---
* Response  

**Status** 
>**성공 :** 201 (Created)
>**실패 :** 409 (Conflict)  

**Content-type :** application/json; charset=utf-8
```js
// 정상 
{
   success: true,
   msg: "회원가입이 정상 처리 되었습니다."
}

// 실패 (중복된 아이디)
{
   success: false,
   msg: "이미 존재하는 아이디 입니다."
}

// 실패 (중복된 이메일)
{
   success: false,
   msg: "이미 가입된 이메일 입니다."
}

// 실패 (중복된 별명)
{
   success: false,
   msg: "이미 사용되고 있는 별명입니다."
}
```
---
- [x] API 구현
- [x] User 모델에 signup() 메서드 구현
- [x] User 모델에 #inspect() 메서드 구현 -> 저장가능한지 검사
- [x] UserStorage 모델에 save() 메서드 구현

**Comment by kimjiwonpg98** [comment]
별명 중복 시 **이미 사용되고 있는 이름 => 이미 사용되고 있는 별명** 으로 변경
