### ISSUE TITLE
[purchaselists] 구매목록 API 구현

### ISSUE THREAD

**Issue by JeongWonji** [wooahan-agile/idu-market-server#38]
## 📍 목적
> 구매목록 조회 , 추가 api 구현

<br>

### 💡 API 명세서
> 1. 구매목록 조회 API
* Request

**URL :**  /api/purchase-list/:studentId ex) ```/api/purchase-list/:wonji```
**Method :** GET
**Content-type :** application/json; charset=utf-8

<br>

* Response  

**Status** 
>**성공 :** 200 (OK)
>**실패 :** 실패의 경우는 없습니다.

**Content-type :** application/json; charset=utf-8

* 성공
```js
{
   success: Boolean,
   msg: String,
   purchaseLists: Array
}
```
* 예시
```js
{
    "success": true,
    "msg": "구매목록 조회 성공했습니다.",
    "purchaseList": [
         {
            "num": 10,
            "buyerId": "test2",
            "buyerName": "hi"
            "thumbnail": "https://woowahan-agile~",
            "title": "스위프트로 아이폰 개발하기4 팝니다",
            "hit": 107,
            "price": "25,000",
            "name": "book",
            "commentCount": 5,
            "inDate": "2021-03-10 07:32:31",
            "sellerId": "test1"
            "sellerName": "HIHI",
            "profilePath": "~~"
        }
    ]
}
```

* ```content```로 검색한 결과가 없을 경우
```js
{
    "success": true,
    "purchaseList": [ ]
}
```

<br>

* 실패
서버의 잘못(DB 조회를 잘못하는 등)인 경우 밖에 존재하지 않는다고 판단하였음. 
따라서 success는 true 밖에 존재하지 않음.

* content로 검색된 내역이 없을 경우 purchaseList의 key로 빈 배열을 응답합니다.
정말 최악의 경우를 생각해서 API를 만들어 두긴 했습니다.

```js
{
   msg: String
}
```

* 예시
```js
{
   msg: "알 수 없는 응답입니다. 서버 개발자에게 문의해주십시오."
}
```

<br>
<br>

### 💡 API 명세서
> 2. 구매목록 생성 API
* Request

**URL :**  /api/purchase-list ex) ```/api/purchase-list```
**Method :** POST
**Content-type :** application/json; charset=utf-8

```js
{
   boardNum:  Number (게시판 주요키),
   studentId:  String (구매자라고 선택된 ID)
}
```
* 예시
```json
{
   "boardNum": 856,
   "studentId": "202016709"
}
```

<br>

* Response  

**Status** 
>**성공 :** 201 (Created)
>**실패 :** 409 (Conflict)

**Content-type :** application/json; charset=utf-8

* 성공
```js
{
   success: Boolean,
   msg: String
}
```
* 예시
```js
{
   success: true,
   msg: "구매목록에 저장 되었습니다"
}
```

<br>

* 실패

1. 구매목록에 저장되어 있을 경우
```js
{
   success: Boolean,
   msg: String (실패 원인)
}
```
* 예시
```js
{
   success: false,
   msg: "이미 구매목록에 저장되어 있습니다."
}
```

2. 게시판이 존재하지 않을 경우
 
```js
{
   success: Boolean,
   msg: String (실패 원인)
}
```
* 예시
```js
{
   success: false,
   msg: "게시판이 존재하지 않습니다."
}

3. status가 변하지 않았을 경우
```js
{
   success: Boolean,
   msg: String (실패 원인)
}
```
* 예시
```js
{
   success: false,
   msg: "구매목록에는 저장되었지만 status가 변경되지 않았습니다. 문의주세요."
}

```

<br>
<br>

### 💡 API 명세서
> 3. 글 상태 변경  API
* Request

**status**
|번호|상태|
|--|--|
|0|판매중|
|1|예약중|
|2|거래완료 선택창|
|3|거래완료|

**URL :**  /api/boards/:categoryName/:num/status ex) ```/api/boards/1/9/status```
**Method :** PATCH
**Content-type :** application/json; charset=utf-8

```js
{
   status: num (0~3)
}
```
* 예시
```js
 {
   status: 2
}
```

<br>

* Response  

**Status** 
>**성공 :** 200 (OK)
>**실패 :** 400 (Bad Request)

**Content-type :** application/json; charset=utf-8

* 성공
```js
{
   success: Boolean,
  status: Number,
   msg: String
}
```
* 예시
```js
{
   success: true,
   status: 2,
   msg: "status 변경 성공"
}
```

<br>

* 실패
```js
{
   success: Boolean,
   msg: String (실패 원인)
}
```
* 예시
```js
{
   success: false,
   msg: "status 변경 실패"
}
```

<br>
<br>

### 💡 API 명세서
> 4. 구매 희망자 목록 조회 (상태 변경 후 구매자 선택) API
* Request

**URL :**  /api/boards/:categoryName/:num/comments ex) ```/api/boards/1/9/comments```
**Method :** GET
**Content-type :** application/json; charset=utf-8

* Response  

**Status** 
>**성공 :** 200 (OK)
>**실패 :** 400 (Bad Request)

**Content-type :** application/json; charset=utf-8

* 성공
```js
{
   success: Boolean,
   msg: String,
   buyers:[
        {
            "nickname": string,
            "id": string,
        },
        {
            "nickname": string,
            "id": string,
        }
    ]
}
```
* 예시
```js
{
   success: true,
   msg: "구매 희망자 조회에 성공하셨습니다.",
   buyers: [
        {
            "nickname": "핵주먹",
            "id": "202016709",
        },
        {
             "nickname": "꿀주먹",
            "id": "202014283",
        }
    ]
}
```

<br>

* 실패
```js
{
   success: Boolean,
   msg: String (실패 원인)
}
```
* 예시
```js
{
   success: false,
   msg: "댓글이 없음"
}
```

<br>
<br>

**Comment by JeonSoongu** [comment]
거래완료 후 구매자 선택 시 아이디에서 닉네임 선택으로 변경
